CREATE DATABASE IF NOT EXISTS bbdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'bbdb'@'%' IDENTIFIED BY "bbdbpass";

GRANT ALL PRIVILEGES ON bbdb.* TO 'bbdb'@'%';

FLUSH PRIVILEGES;